### PR TITLE
Taking in the reddit username, making Api call getting authorization token, making another Api call with that auth token to get user info and filtering data to get their post title from that.

### PR DESCRIPTION
**Pull request by MohammadOsama15**
The code I'm committing first goes and generates the Authorization token using your Secret Key, Client ID, Reddit username and Reddit password. Then we use that authorization token to make a call for the reddit username that is provided in the search page. Then it goes and gets all the info about the user then we filter everything to just get their post titles that we needed to do ML on to generate sentiment. This is on the console get all their post titles only

image

This is how it looks like on the search page all the titles are up down for some reason. (not pretty i know but works):

image

This is that random reddit users posts screenshot below:

image

### CODE REVIEW

**Review by MahreenAsghar — COMMENTED** [review]
Can you please update the README.md with the instructions on how to add and where to get the CLIENT_ID, SECRET_KEY, username and password to make the API call.

**Comment by MohammadOsama15** [comment]
> Can you please update the README.md with the instructions on how to add and where to get the CLIENT_ID, SECRET_KEY, username and password to make the API call.

Yes, I'll update that as soon as I can!

**Comment by jayliu223** [comment]
Would you be able to modify the function such that we can specify the number of posts we wish to pull?
For example, if I import your function with an alias, I would like to do something like:
get_post(cap=50, sorted-by="type").

The sortation component could come at a much later date, but being able to specify up to n posts as input parameter can be very handy.

**Comment by MohammadOsama15** [comment]
> > Can you please update the README.md with the instructions on how to add and where to get the CLIENT_ID, SECRET_KEY, username and password to make the API call.
> 
> Yes, I'll update that as soon as I can!

> > Can you please update the README.md with the instructions on how to add and where to get the CLIENT_ID, SECRET_KEY, username and password to make the API call.
> 
> Yes, I'll update that as soon as I can!

I have updated the README.md as requested!

**Comment by MohammadOsama15** [comment]
> Would you be able to modify the function such that we can specify the number of posts we wish to pull? For example, if I import your function with an alias, I would like to do something like: get_post(cap=50, sorted-by="type").
> 
> The sortation component could come at a much later date, but being able to specify up to n posts as input parameter can be very handy.

The parameter in the get_post(query) is passing the reddit username, that which the user of our website(Earlybird) puts in the search bar. Do we want to give them the capabilities of asking how many post titles they want and which type they want it sorted by?

**Comment by jayliu223** [comment]
You can wrap that function in another to restrict what inputs folks submitting queries through the web can make, but having this sort of features is in my opinion very important.

If we abstract this idea like SQL, it would be restricting and parameterizing query statements for users instead of restricting access for everyone.

For instance:

def query_main(subreddit, user, num_posts, sort_by):
   implementation here

def query_visitor(subreddit, user):
   num_posts = some_value
   default_sort=""
   query_main(subreddit, user, num_posts=num_posts, sort_by=default_sort

**Comment by MohammadOsama15** [comment]
> You can wrap that function in another to restrict what inputs folks submitting queries through the web can make, but having this sort of features is in my opinion very important.
> 
> If we abstract this idea like SQL, it would be restricting and parameterizing query statements for users instead of restricting access for everyone.
> 
> For instance:
> 
> def query_main(subreddit, user, num_posts, sort_by): implementation here
> 
> def query_visitor(subreddit, user): num_posts = some_value default_sort="" query_main(subreddit, user, num_posts=num_posts, sort_by=default_sort

Sounds good, taken care of!

**Comment by jayliu223** [comment]
> > You can wrap that function in another to restrict what inputs folks submitting queries through the web can make, but having this sort of features is in my opinion very important.
> > If we abstract this idea like SQL, it would be restricting and parameterizing query statements for users instead of restricting access for everyone.
> > For instance:
> > def query_main(subreddit, user, num_posts, sort_by): implementation here
> > def query_visitor(subreddit, user): num_posts = some_value default_sort="" query_main(subreddit, user, num_posts=num_posts, sort_by=default_sort
> 
> Sounds good, taken care of!

Fantastic! I see pagination working and I can pull up to a cap. This should improve response time and add flexibility to our app.

**Comment by jayliu223** [comment]
Please resolve merge conflict!

**Review by jayliu223 — APPROVED** [review]

**Pull request merged**
